version: "3.7"

services:

  influxdb:

    image: influxdb
    container_name: influxdb
    restart: always

    ports:
      - 8086:8086

    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_DB: "weather"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "adminadmin"

    volumes:
      - ./data/influxdb:/var/lib/influxdb


  chronograf:

    image: chronograf
    container_name: chronograf
    restart: always

    ports:
      - 8888:8888

    environment:
      INFLUXDB_URL: "http://influxdb:8086"
      #KAPACITOR_URL: "http://kapacitor:9092"

    volumes:
      - ./data/chronograf:/var/lib/chronograf

    depends_on:
      - influxdb


  telegraf:
  
      image: telegraf
      container_name: telegraf
      restart: always
  
      environment:
        HOST_NAME: "telegraf"
        INFLUXDB_URL: "http://influxdb:8086"
        INFLUXDB_DATABASE: "weather"
        INFLUXDB_USERNAME: "admin"
        INFLUXDB_PASSWORD: "adminadmin"
  
      volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf

      depends_on:
        - influxdb
